name: 'Run Polypheny'
description: 'Start a Polypheny instance for a task'
inputs:
  java:
    description: 'The java executable to use'
    required: false
    default: 'java'
  jar:
    description: 'Polypheny JAR file to use'
    required: true
  cmd:
    description: 'Command to run'
    required: true
  autodocker:
    description: 'Automatically connect to local Docker instance'
    required: false
    default: 'true'
  working-directory:
    description: 'The working directory of the task'
    required: false
    default: ''
  default-store:
    description: 'The default store setting for Polypheny'
    required: false
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'
